// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQnSJm4f-2AFY3h8ZJp5NofqMLfKsfrOk',
    appId: '1:282001161297:web:e8dcd197cf3ecd563a8c70',
    messagingSenderId: '282001161297',
    projectId: 'gapo-test',
    authDomain: 'gapo-test.firebaseapp.com',
    databaseURL: 'https://gapo-test-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gapo-test.appspot.com',
    measurementId: 'G-PQ9VT3RBXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMU1xl2YkuX7MBwY_vtCzvyo8MHGG7PXo',
    appId: '1:282001161297:android:fbeca2ba6cd5cbd43a8c70',
    messagingSenderId: '282001161297',
    projectId: 'gapo-test',
    databaseURL: 'https://gapo-test-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gapo-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwbeDo1C4DCVFRtKEWk42TSCUNt0hjalU',
    appId: '1:282001161297:ios:896962fa0d2bdefe3a8c70',
    messagingSenderId: '282001161297',
    projectId: 'gapo-test',
    databaseURL: 'https://gapo-test-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gapo-test.appspot.com',
    androidClientId: '282001161297-53qm83885gj3brevl8dtm4l7rs7mra0p.apps.googleusercontent.com',
    iosClientId: '282001161297-2rftb6c95pfl0a102op0bedkadiim728.apps.googleusercontent.com',
    iosBundleId: 'com.example.toannmFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwbeDo1C4DCVFRtKEWk42TSCUNt0hjalU',
    appId: '1:282001161297:ios:3edeea0a2bfecbb33a8c70',
    messagingSenderId: '282001161297',
    projectId: 'gapo-test',
    databaseURL: 'https://gapo-test-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gapo-test.appspot.com',
    androidClientId: '282001161297-53qm83885gj3brevl8dtm4l7rs7mra0p.apps.googleusercontent.com',
    iosClientId: '282001161297-tu1tcupi2ko8k87qqhhircmhv3ipdgur.apps.googleusercontent.com',
    iosBundleId: 'com.example.toannmFirebase.RunnerTests',
  );
}
